[workspace]
members = [
    "dash-spv-apple-bindings",
    "dash-spv-example-app",
    "dash-spv-masternode-processor",
    "reachability",
]

[workspace.package]
authors = ["Vladimir Pirogov <vladimir.pirogov@dash.org>"]
description = "Dash SPV core"
documentation = "https://dashcore.readme.io/docs"
homepage = "https://github.com/dashpay/dash-shared-core"
license = "MIT"
keywords = ["crypto", "dash", "spv"]

[profile.release]
lto = "thin"
opt-level = 3
